import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar utama di bagian atas */}
        <nav
          style={{
            width: '100%',
            padding: '1rem 2rem',
            background: '#f4f4f5',
            borderBottom: '1px solid #e5e7eb',
            marginBottom: '2rem',
            display: 'flex',
            position: 'relative',
          }}
        >
          {/* Nama di kiri */}
          <span style={{ color: '#222', fontWeight: 600, position: 'absolute', left: '3.5rem' }}>Wildan</span>
          {/* Menu di tengah */}
          <div style={{ display: 'flex', gap: '1.5rem', margin: '0 auto' }}>
            <a href="/" style={{ textDecoration: 'none', color: '#222', fontWeight: 500 }}>Home</a>
            <a href="/about" style={{ textDecoration: 'none', color: '#222', fontWeight: 500 }}>About</a>
          </div>
        </nav>

        {/* Konten utama halaman */}
        {children}

        {/* Footer di bagian bawah */}
        <footer
          style={{
            width: '100%',
            padding: '1rem 2rem',
            background: '#f4f4f5',
            borderTop: '1px solid #e5e7eb',
            marginTop: '2rem',
            textAlign: 'center',
            color: '#666',
            fontSize: '1rem',
          }}
        >
          © {new Date().getFullYear()} MyPorto. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
